{
  "package_id": "libcerf",
  "schema_version": 1,
  "sources": [
    {
      "digests": {
        "sha256": "7cbece26ad94bd375eb81fee2b540d0ef68bbeb0994358e57bd588173f96b8ec"
      },
      "filename": "libcerf-v3.3.tar.gz",
      "id": "source0",
      "kind": "upstream-release",
      "redistribution": {
        "allowed": true,
        "reason": "The publisher tag archive is redistributable under MIT."
      },
      "signature": null,
      "url": "https://jugit.fz-juelich.de/mlz/libcerf/-/archive/v3.3/libcerf-v3.3.tar.gz",
      "version": "3.3"
    }
  ]
}
