{
  "package_id": "libcerf",
  "schema_version": 1,
  "sources": [
    {
      "digests": {
        "sha256": "9071fd4c02f5a57b909ad733dd7c8ac321642464365691b181c23d66ac6730f6"
      },
      "filename": "libcerf-v3.7.tar.gz",
      "id": "source0",
      "kind": "upstream-release",
      "redistribution": {
        "allowed": true,
        "reason": "The publisher tag archive is redistributable under MIT."
      },
      "signature": null,
      "url": "https://jugit.fz-juelich.de/mlz/libcerf/-/archive/v3.7/libcerf-v3.7.tar.gz",
      "version": "3.7"
    }
  ]
}
