# SPDX-License-Identifier: Apache-2.0
Name:           gengetopt
Version:        2.23
Release:        1%{?dist}
Summary:        Generate C command-line parsers using getopt_long
License:        GPL-3.0-or-later
URL:            https://www.gnu.org/software/gengetopt/
Source0:        gengetopt-%{version}.tar.xz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  texinfo

%description
GNU gengetopt generates C source code for parsing command-line options with
getopt_long. Code generated by gengetopt is not subject to gengetopt's GPL.

%prep
%autosetup -p1

%build
%configure
# Upstream documents that the generated-source build is not parallel-safe.
%{__make}

%install
%make_install
rm -f %{buildroot}%{_infodir}/dir
rm -rf %{buildroot}%{_docdir}/gengetopt

%check
# The same generated-source constraint applies to the complete test matrix.
%{__make} check

%files
%license COPYING LICENSE
%doc AUTHORS ChangeLog NEWS README THANKS TODO doc/README.example doc/index.html
%{_bindir}/gengetopt
%{_datadir}/gengetopt/
%{_infodir}/gengetopt.info*
%{_mandir}/man1/gengetopt.1*

%changelog
* Wed Aug 12 2026 openEuler RISC-V Maintainers <noreply@example.invalid> - 2.23-1
- Initial openEuler RISC-V package with the complete serial upstream test suite.
