# SPDX-License-Identifier: Apache-2.0
Name:           xapp
Version:        3.2.2
Release:        3%{?dist}
Summary:        Common library for X-Apps project
License:        LGPL-3.0-or-later
URL:            https://github.com/linuxmint/xapp
Source0:        xapp-3.2.2.tar.gz
BuildRequires:  gcc
BuildRequires:  gettext
BuildRequires:  gobject-introspection-devel
BuildRequires:  make
BuildRequires:  meson
BuildRequires:  ninja-build
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(cairo-gobject)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(dbusmenu-gtk3-0.4)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gio-unix-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gmodule-2.0)
BuildRequires:  pkgconfig(gtk+-3.0)
BuildRequires:  pkgconfig(libgnomekbdui)
BuildRequires:  pkgconfig(pygobject-3.0)
BuildRequires:  pkgconfig(x11)
BuildRequires:  python3-devel
BuildRequires:  vala

%description
Common library for X-Apps project

%prep
%autosetup -p1

%build
%meson
%meson_build

%install
%meson_install
find %{buildroot} \( -type f -o -type l \) -printf '/%%P\n' | LC_ALL=C sort > %{name}.files
test -s %{name}.files

%check
%meson_test

%files -f %{name}.files
%{python3_sitearch}/gi/overrides/__pycache__/XApp.*
%license COPYING
%license COPYING.LESSER
%doc README.md
%doc AUTHORS
%doc ChangeLog

%changelog
* Wed Sep 02 2026 openEuler RISC-V Maintainers <noreply@example.invalid> - 3.2.2-3
- Own Python override bytecode generated by RPM post-processing.

* Wed Sep 02 2026 openEuler RISC-V Maintainers <noreply@example.invalid> - 3.2.2-2
- Declare the complete required Meson, introspection, and binding build closure.

* Wed Aug 26 2026 openEuler RISC-V Maintainers <noreply@example.invalid> - 3.2.2-1
- Initial openEuler RISC-V package from the full package inventory.
